file_format: "1"
id: twist40
name: twist40
type: shield
url: https://github.com/GEIGEIGEIST/KLOR
requires: [Nice!Nano]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - twist40
